<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('MemberModel');
       $this->load->model('AdminModel');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			//print_r("berhasil login");
			$status=$this->session->userdata('status');
			if ($status="member") {
			redirect('Home');
				
			}else{
				redirect("Dashboard");
				
			}
		}
		
		if(!$this->input->post())
		{
			$this->load->view('LoginBenar');
		}
		else
		{
			$username=$this->input->post('username');
			$password=$this->input->post('password');
			
			$cek_login=$this->MemberModel->cek_login($username,$password);
			$cek_login_admin=$this->AdminModel->cek_login($username,$password);

			if(!empty($cek_login))
				
			{
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('member',$cek_login);
				$this->session->set_userdata('status','member');
				$data=array();

				$this->session->set_userdata('cart',$data);
				redirect("Home");
				//print_r("berhasil login member");
			}
			else if (!empty($cek_login_admin)) {
			$this->session->set_userdata('logined', true);
				$this->session->set_userdata('admin',$cek_login_admin);
				$this->session->set_userdata('status',$cek_login_admin->status);
				redirect("Dashboard");
				

			}
			else 
			{
$this->session->set_flashdata('gagal','<div class="alert alert-danger"> <Strong>Gagal Login</strong> username dan password anda salah. </div>');

				redirect("Login");

							}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('admin');
		$this->session->unset_userdata('member');

		$this->session->unset_userdata('status');
		$this->session->unset_userdata('cart');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */